# Config overrides for development.
url                      : http://localhost:4000
analytics:
  provider: google-universal
  google:
    tracking_id:
comments:
  provider: disqus
  disqus:
    shortname:
